name: ORLEN retail fuel prices → ntfy.sh

on:
  schedule:
    # 05:00 UTC = 07:00 Europe/Warsaw (czas letni)
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  retail-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Install grep (z obsługą PCRE) & curl
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y grep curl

      - name: Fetch ORLEN prices and push to ntfy
        shell: bash
        run: |
          set -euo pipefail

          # 1) Pobranie strony (dodajemy nagłówek UA dla pewności)
          PAGE=$(curl -fsSL -A "Mozilla/5.0 (GitHub Actions)" \
                   'https://www.autocentrum.pl/stacje-paliw/pkn-orlen/')

          # 2) Usunięcie tagów + zwinięcie w jedną linię
          TEXT=$(echo "$PAGE" \
                   | sed 's/<[^>]*>/ /g' \
                   | tr '\n' ' ' \
                   | tr -s ' ')

          # 3) Funkcja ekstrakcji liczby „X,YY” po wzorcu
          extract() {                                        # $1 = regex
            echo "$TEXT" \
              | grep -oPi "$1\\s*[0-9],[0-9]{2}" \
              | head -n1 \
              | grep -oP '[0-9],[0-9]{2}' || true
          }

          PB95=$(extract 'pbs')        # „pb ” (spacja po pb ⇒ nie złapie pb+)
          PB98=$(extract 'pb+')        # „pb+”
          ON=$(extract  'ons')         # „on ”
          ONPLUS=$(extract 'on+')      # „on+”
          LPG=$(extract  'lpg')          # „lpg”

          TODAY=$(date +%F)
          MSG=$(printf 'Średnie detaliczne ceny paliw – ORLEN (%s)\nPb95 : %s zł/l\nPb98 : %s zł/l\nON   : %s zł/l\nON+  : %s zł/l\nLPG  : %s zł/l\n' \
                 "$TODAY" "${PB95:-brak}" "${PB98:-brak}" "${ON:-brak}" "${ONPLUS:-brak}" "${LPG:-brak}")

          # 4) Wysłanie powiadomienia
          curl -H "Title: Ceny detaliczne ORLEN" \
               -H "Priority: 3" \
               -d "$MSG" \
               https://ntfy.sh/paliwa
