name: ORLEN retail fuel prices → ntfy.sh

on:
  schedule:
    # 05:00 UTC = 07:00 Europe/Warsaw (czas letni)
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  retail-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Zainstaluj jq
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq

      - name: Pobierz ceny detaliczne i wyślij powiadomienie
        shell: bash
        run: |
          set -euo pipefail

          # 1) HTML z AutoCentrum (średnie ceny ORLEN)
          PAGE=$(curl -fsSL 'https://www.autocentrum.pl/stacje-paliw/pkn-orlen/')

          # 2) Funkcja ekstrakcji pierwszej liczby po nazwie paliwa
          extract_price() {                               # $1 = regex
            echo "$PAGE" | awk -v RS='<[^>]*>' '
              {gsub(/&nbsp;| /,"")}
              $0 ~ /'"$1"'/ {getline; print; exit}
            ' | grep -oE '[0-9],[0-9]{2}' || true
          }

          PB95=$(extract_price 'pb[^a-z]')   # Pb95
          PB98=$(extract_price 'pb\\+')      # Pb98 / Verva
          ON=$(extract_price  'on[^a-z]')    # ON
          ONPLUS=$(extract_price 'on\\+')    # ON+
          LPG=$(extract_price  'lpg')        # LPG

          TODAY=$(date +'%Y-%m-%d')

          # 3) Tekst powiadomienia (wielolinijkowy string w zmiennej)
          MSG="Średnie detaliczne ceny paliw – ORLEN (${TODAY})
Pb95 : ${PB95:-brak} zł/l
Pb98 : ${PB98:-brak} zł/l
ON   : ${ON:-brak} zł/l
ON+  : ${ONPLUS:-brak} zł/l
LPG  : ${LPG:-brak} zł/l"

          # 4) Wyślij do ntfy.sh
          curl -H "Title: Ceny detaliczne ORLEN" \
               -H "Priority: 3" \
               -d "$MSG" \
               https://ntfy.sh/paliwa
