name: ORLEN retail fuel prices → ntfy.sh

on:
  schedule:
    # 05:00 UTC ≙ 07:00 Europe/Warsaw (czas letni)
    - cron: '0 5 * * *'
  workflow_dispatch: {}   # pozwala uruchomić ręcznie z karty Actions

jobs:
  retail-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Zainstaluj narzędzia tekstowe
        run: sudo apt-get update && sudo apt-get -y install jq

      - name: Pobierz detaliczne ceny ORLEN i wyślij powiadomienie
        env:
          NTFY_URL: https://ntfy.sh/paliwa
        shell: bash
        run: |
          set -euo pipefail

          # 1) Pobierz kod HTML strony AutoCentrum z cenami ORLEN
          PAGE=$(curl -fsSL 'https://www.autocentrum.pl/stacje-paliw/pkn-orlen/')

          # 2) Funkcja pomocnicza: wyciągnij pierwszą liczbę z danej sekcji
          extract_price () {  # $1 = wzorzec (pb|pb\+|on\b|on\+|lpg)
            echo "$PAGE" \
              | awk -v RS='<[^>]*>' '{gsub(/&nbsp;| /,""); if ($0 ~ /'$1'/) {getline; print; exit}}' \
              | grep -oE '[0-9],[0-9]{2}'
          }

          PB95=$(extract_price 'pb[^a-z]')   # „pb” (95)
          PB98=$(extract_price 'pb\+')       # „pb+” (Verva 98)
          ON=$(extract_price  'on[^a-z]')    # „on”  (Ekodiesel)
          ONPLUS=$(extract_price 'on\+')     # „on+” (Verva ON)
          LPG=$(extract_price  'lpg')        # „lpg”

          # 3) Zbuduj treść powiadomienia
          TODAY=$(date +'%Y-%m-%d')
          MSG=$(cat <<EOF
Średnie detaliczne ceny paliw – ORLEN (${TODAY})
Pb95 : ${PB95} zł/l
Pb98 : ${PB98:-brak} zł/l
ON   : ${ON} zł/l
ON+  : ${ONPLUS:-brak} zł/l
LPG  : ${LPG:-brak} zł/l
EOF
          )

          # 4) Wyślij do ntfy.sh (z uwzględnieniem Basic Auth, jeśli skonfigurowano)
          CURL_OPTS=(-H "Title: Ceny detaliczne ORLEN" -H "Priority: 3" -d "$MSG")
          if [[ -n "${NTFY_USER:-}" && -n "${NTFY_PASS:-}" ]]; then
            CURL_OPTS=(-u "${NTFY_USER}:${NTFY_PASS}" "${CURL_OPTS[@]}")
          fi
          curl -fsSL "${CURL_OPTS[@]}" "${NTFY_URL}"

