name: ORLEN retail fuel prices → ntfy.sh

on:
  schedule:
    # 05:00 UTC = 07:00 Europe/Warsaw (czas letni)
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  retail-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq

      - name: Fetch prices and push to ntfy
        shell: bash
        run: |
          set -euo pipefail

          # 1) HTML z AutoCentrum
          PAGE=$(curl -fsSL 'https://www.autocentrum.pl/stacje-paliw/pkn-orlen/')

          # 2) Funkcja ekstrakcji pierwszej liczby po nazwie paliwa
          extract() {                               # $1 = regex
            echo "$PAGE" | awk -v RS='<[^>]*>' '
              {gsub(/&nbsp;| /,"")}
              $0 ~ /'"$1"'/ {getline; print; exit}
            ' | grep -oE '[0-9],[0-9]{2}' || true
          }

          PB95=$(extract 'pb[^a-z]')
          PB98=$(extract 'pb\\+')
          ON=$(extract  'on[^a-z]')
          ONPLUS=$(extract 'on\\+')
          LPG=$(extract  'lpg')

          TODAY=$(date +%F)

          # 3) Wiadomość (HEREDOC z poprawnym wcięciem)
          read -r -d '' MSG << EOF
Średnie detaliczne ceny paliw – ORLEN (${TODAY})
Pb95 : ${PB95:-brak} zł/l
Pb98 : ${PB98:-brak} zł/l
ON   : ${ON:-brak} zł/l
ON+  : ${ONPLUS:-brak} zł/l
LPG  : ${LPG:-brak} zł/l
EOF

          # 4) Push do ntfy
          curl -H "Title: Ceny detaliczne ORLEN" \
               -H "Priority: 3" \
               -d "$MSG" \
               https://ntfy.sh/paliwa
