name: ORLEN retail fuel prices → ntfy.sh

on:
  schedule:
    # 05:00 UTC ≙ 07:00 Europe/Warsaw (czas letni)
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  retail-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq

      - name: Fetch ORLEN retail prices and push to ntfy
        shell: bash
        run: |
          set -euo pipefail

          # 1) Pobierz stronę z cenami
          PAGE=$(curl -fsSL 'https://www.autocentrum.pl/stacje-paliw/pkn-orlen/')

          # 2) Funkcja do wyciągania pierwszej liczby po nazwie paliwa
          extract() {                                   # $1 = regex
            echo "$PAGE" | awk -v RS='<[^>]*>' '
              {gsub(/&nbsp;| /,"")}
              $0 ~ /'"$1"'/ {getline; print; exit}
            ' | grep -oE "[0-9],[0-9]{2}" || true
          }

          PB95=$(extract 'pb[^a-z]')
          PB98=$(extract 'pb\\+')
          ON=$(extract 'on[^a-z]')
          ONPLUS=$(extract 'on\\+')
          LPG=$(extract 'lpg')

          TODAY=$(date +%F)

          # 3) Zbuduj wiadomość (printf = brak problemu z wcięciami YAML)
          MSG=$(printf 'Średnie detaliczne ceny paliw – ORLEN (%s)\nPb95 : %s zł/l\nPb98 : %s zł/l\nON   : %s zł/l\nON+  : %s zł/l\nLPG  : %s zł/l\n' \
            "$TODAY" "${PB95:-brak}" "${PB98:-brak}" "${ON:-brak}" "${ONPLUS:-brak}" "${LPG:-brak}")

          # 4) Wyślij powiadomienie
          curl -H "Title: Ceny detaliczne ORLEN" \
               -H "Priority: 3" \
               -d "$MSG" \
               https://ntfy.sh/paliwa
